"""Putting suwgit on PATH and into the Task Scheduler.

Both steps are idempotent: `just install` may be re-run whenever the config
needs changing, and it must not pile up launchers or duplicate tasks.

The Python that runs the install is the Python the launchers and the task use —
its path is written into them, the way the Linux unit baked in the shell's PATH.
A scheduled task does not see Git Bash's PATH, and must not depend on which
`python` happens to come first in it.
"""

from __future__ import annotations

import csv
import datetime as dt
import os
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

from . import paths

# A sweep that is still running when the next one is due is left alone (IgnoreNew),
# and one that hangs — a model that never answers — is stopped after this long.
EXECUTION_LIMIT = "PT2H"

TASK_TEMPLATE = """<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>suwgit: commits registered repositories with LLM-written messages</Description>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <StartBoundary>{start}</StartBoundary>
      <Repetition>
        <Interval>{interval}</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <Enabled>true</Enabled>
    </TimeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <Enabled>{enabled}</Enabled>
    <ExecutionTimeLimit>{limit}</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>{command}</Command>
      <Arguments>{arguments}</Arguments>
      <WorkingDirectory>{workdir}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""

BASH_SHIM_TEMPLATE = """#!/usr/bin/env bash
# Generated by `just install` in {repo} — re-run it rather than editing this file.
exec "{python}" -X utf8 "{entrypoint}" "$@"
"""

CMD_SHIM_TEMPLATE = """@rem Generated by `just install` in {repo} - re-run it rather than editing this file.
@"{python}" -X utf8 "{entrypoint}" %*
"""

# Recognises our own launchers, so uninstall never deletes someone else's file.
SHIM_MARKER = "Generated by `just install`"


def python_exe() -> Path:
    """The interpreter behind this process — outside any venv it was started from."""
    return Path(getattr(sys, "_base_executable", sys.executable))


def pythonw_exe() -> Path:
    """The windowless twin of python.exe: a console window every 90 minutes is not quiet."""
    python = python_exe()
    windowless = python.with_name(python.name.replace("python", "pythonw", 1))
    return windowless if windowless.exists() else python


def interval_minutes(hours: float) -> int:
    """Task Scheduler repeats in whole minutes, one at the least."""
    return max(1, round(hours * 60))


def render_task(interval_hours: float, enabled: bool, now: dt.datetime | None = None) -> str:
    """The task: `suwgit sweep` every interval, starting a minute from now.

    StartWhenAvailable makes up for a sweep missed while the machine was off or
    asleep, and the InteractiveToken logon means no stored password: the task
    runs as you, while you are logged in — which is when you have work to commit.
    """
    start = (now or dt.datetime.now().astimezone()).replace(second=0, microsecond=0) + dt.timedelta(minutes=1)
    return TASK_TEMPLATE.format(
        # Local wall-clock time, no offset: the scheduler then keeps the same hour across DST.
        start=start.replace(tzinfo=None).isoformat(),
        interval=f"PT{interval_minutes(interval_hours)}M",
        enabled="true" if enabled else "false",
        limit=EXECUTION_LIMIT,
        command=escape(str(pythonw_exe())),
        arguments=escape(f'-X utf8 "{paths.ENTRYPOINT}" sweep'),
        workdir=escape(str(paths.REPO_ROOT)),
    )


def render_shims() -> dict[Path, str]:
    values = {"repo": paths.REPO_ROOT, "python": python_exe(), "entrypoint": paths.ENTRYPOINT}
    return {
        paths.BASH_SHIM: BASH_SHIM_TEMPLATE.format(**values),
        paths.CMD_SHIM: CMD_SHIM_TEMPLATE.format(**values),
    }


def _is_ours(path: Path) -> bool:
    try:
        return SHIM_MARKER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def link_into_path() -> tuple[bool, str]:
    """Write the two launchers into ~/.local/bin."""
    paths.BIN_DIR.mkdir(parents=True, exist_ok=True)
    shims = render_shims()
    for shim in shims:
        if shim.exists() and not _is_ours(shim):
            return False, f"{shim} exists and is not ours — remove it and re-run `just install`"
    for shim, body in shims.items():
        # LF for both: bash chokes on a CR, and cmd reads either.
        shim.write_text(body, encoding="utf-8", newline="\n")
    return True, f"launchers in {paths.BIN_DIR} (suwgit for Git Bash, suwgit.cmd for cmd/PowerShell)"


def path_contains_local_bin() -> bool:
    def norm(p: str) -> str:
        return os.path.normcase(os.path.realpath(p))

    return norm(str(paths.BIN_DIR)) in {norm(p) for p in os.environ.get("PATH", "").split(os.pathsep) if p}


def _schtasks(*args: str) -> tuple[int, str]:
    try:
        done = subprocess.run(
            ["schtasks", *args],
            capture_output=True,
            # schtasks answers in the console's OEM code page, not UTF-8.
            encoding="oem",
            errors="replace",
            creationflags=subprocess.CREATE_NO_WINDOW,
            check=False,
        )
    except OSError as exc:
        return 1, str(exc)
    return done.returncode, (done.stderr or done.stdout).strip()


def install_task(interval_hours: float, enabled: bool) -> tuple[bool, str]:
    """Create or replace the task. schtasks only takes a definition this detailed as an XML file."""
    paths.STATE_DIR.mkdir(parents=True, exist_ok=True)
    xml_file = paths.STATE_DIR / "task.xml"
    xml_file.write_text(render_task(interval_hours, enabled), encoding="utf-16")
    try:
        code, detail = _schtasks("/Create", "/TN", paths.TASK_NAME, "/XML", str(xml_file), "/F")
    finally:
        xml_file.unlink(missing_ok=True)
    if code != 0:
        return False, f"could not register the scheduled task: {detail}"
    every = f"every {interval_minutes(interval_hours)} min"
    if not enabled:
        return True, f"scheduled task '{paths.TASK_NAME}' registered but disabled ({every} once enabled)"
    return True, f"scheduled task '{paths.TASK_NAME}' sweeps {every} while you are logged in"


def uninstall_task() -> list[str]:
    """Delete the task. Returns what was actually done."""
    code, _ = _schtasks("/Delete", "/TN", paths.TASK_NAME, "/F")
    return [f"deleted scheduled task '{paths.TASK_NAME}'"] if code == 0 else []


def task_exists() -> bool:
    return _schtasks("/Query", "/TN", paths.TASK_NAME)[0] == 0


def unlink_from_path() -> list[str]:
    """Remove our launchers — but never a file someone else put there."""
    done = []
    for shim in (paths.BASH_SHIM, paths.CMD_SHIM):
        if not shim.exists():
            continue
        if _is_ours(shim):
            shim.unlink()
            done.append(f"removed {shim}")
        else:
            done.append(f"left {shim} alone — it is not a suwgit launcher")
    return done


def task_status() -> str:
    """'Ready, next run …', or 'not registered'."""
    code, out = _schtasks("/Query", "/TN", paths.TASK_NAME, "/FO", "CSV", "/NH")
    if code != 0:
        return "not registered"
    # Columns by position — the headers are translated on a localised Windows.
    for row in csv.reader(out.splitlines()):
        if len(row) >= 3:
            _name, next_run, status = row[:3]
            return f"{status}, next run {next_run}"
    return "unknown"
